# Generated by Django 2.1.7 on 2019-06-08 00:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField(blank=True)),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dulceria.Combo')),
            ],
        ),
        migrations.CreateModel(
            name='Dulceria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(height_field=400, upload_to='imagenes/', width_field=400)),
                ('eslogan', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Golosina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField(blank=True)),
                ('caducidad', models.DateField(default=datetime.datetime.today)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('dulceria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dulceria.Dulceria')),
            ],
        ),
        migrations.AddField(
            model_name='detallecombo',
            name='golosina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dulceria.Golosina'),
        ),
        migrations.AddField(
            model_name='combo',
            name='dulceria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dulceria.Dulceria'),
        ),
    ]
