# Generated by Django 2.2.2 on 2019-06-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dulceria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dulceria',
            name='logo',
            field=models.ImageField(height_field=4000, upload_to='imagenes/', width_field=4000),
        ),
    ]
