# Generated by Django 2.1.7 on 2019-06-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dulceria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dulceria',
            name='logo',
            field=models.ImageField(blank=True, height_field=400, null=True, upload_to='imagenes/', width_field=400),
        ),
    ]
