# Generated by Django 2.1.7 on 2019-06-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dulceria', '0002_auto_20190607_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golosina',
            name='caducidad',
        ),
    ]
