# Generated by Django 2.2.2 on 2019-06-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dulceria', '0002_auto_20190613_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dulceria',
            name='logo',
        ),
    ]
