# Generated by Django 2.1.7 on 2019-06-16 23:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='tiempoRestante',
        ),
        migrations.AddField(
            model_name='carrito',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cantidadProductos',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Productos'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='entregado',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Facturacion.TarjetaCredito'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='tipoPago',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total'),
        ),
    ]
