# Generated by Django 2.1.7 on 2019-06-17 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_auto_20190616_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('132ed596-6ae9-4c29-b0d4-a9bc42a19136'), editable=False, max_length=40),
        ),
    ]
