# Generated by Django 2.1.7 on 2019-06-19 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0003_auto_20190616_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('409c8d25-fa99-4c07-b9a4-954b93ae7118'), editable=False, max_length=40),
        ),
    ]
