# Generated by Django 2.1.7 on 2019-06-19 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0004_auto_20190618_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('1def48c3-029e-4220-98c8-de3bfb517ad6'), editable=False, max_length=40),
        ),
    ]
