# Generated by Django 2.1.7 on 2019-06-19 01:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0005_auto_20190618_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('067dc2fc-d833-4847-ac3d-42dd90627e05'), editable=False, max_length=40),
        ),
    ]
