# Generated by Django 2.1.7 on 2019-06-19 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0006_auto_20190618_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('892c506d-c84d-4e71-a59d-051f4b121c0a'), editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='lineaventa',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
