# Generated by Django 2.1.7 on 2019-06-19 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0007_auto_20190619_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('93133164-c95b-445b-a487-73e51a5c01bd'), editable=False, max_length=40),
        ),
    ]
