# Generated by Django 2.1.7 on 2019-06-19 21:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0008_auto_20190619_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('0f91b094-466d-4ecc-8cfb-50bc6b8c833b'), editable=False, max_length=40),
        ),
    ]
