# Generated by Django 2.1.7 on 2019-06-19 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0009_auto_20190619_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('8d24322b-89b4-4a87-a9b6-c18f6253f0c4'), editable=False, max_length=40),
        ),
    ]
