# Generated by Django 2.1.7 on 2019-06-19 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0010_auto_20190619_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('330d4231-8efc-4b1c-8d2b-ef1b41639b4f'), editable=False, max_length=40),
        ),
    ]
