# Generated by Django 2.1.7 on 2019-06-19 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0012_auto_20190619_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('a9b081d8-41e0-41ec-ab77-88717083e2e8'), editable=False, max_length=40),
        ),
    ]
