# Generated by Django 2.1.7 on 2019-06-19 23:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0013_auto_20190619_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('f3fcb2d5-18bd-4363-80da-d227b9527f82'), editable=False, max_length=40),
        ),
    ]
