# Generated by Django 2.1.7 on 2019-06-21 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0014_auto_20190619_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('8c299e54-4b63-4f60-b0e6-febbe2f8b5a8'), editable=False, max_length=40),
        ),
    ]
