# Generated by Django 2.1.7 on 2019-06-21 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0016_auto_20190621_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('932765ee-130f-45db-8021-b96a25b506b3'), editable=False, max_length=40, verbose_name='Codigo de Compra'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='lineaventa',
            name='tipoProducto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Producto'),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='ccv',
            field=models.IntegerField(verbose_name='CCV'),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='fechaVencimiento',
            field=models.DateField(verbose_name='Fecha Vencimiento'),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='numero',
            field=models.IntegerField(verbose_name='Numero'),
        ),
    ]
