# Generated by Django 2.1.7 on 2019-06-23 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0017_auto_20190621_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('dc2fc711-e3b0-4bc2-a4b8-77e69e7dccef'), editable=False, max_length=40, verbose_name='Codigo de Compra'),
        ),
    ]
