# Generated by Django 2.1.7 on 2019-06-24 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0018_auto_20190623_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCompra',
            field=models.CharField(default=uuid.UUID('a3f767cd-3fc4-4262-ba11-38158509a39a'), editable=False, max_length=40, verbose_name='Codigo de Compra'),
        ),
    ]
