# Generated by Django 2.1.7 on 2019-06-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boleteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleteria',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Peliculas'),
        ),
    ]
