# Generated by Django 2.1.7 on 2019-06-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boleteria', '0002_auto_20190606_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butaca',
            name='clase',
            field=models.BooleanField(default=True),
        ),
    ]
