# Generated by Django 2.1.7 on 2019-06-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boleteria', '0003_auto_20190607_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='Funcion',
            field=models.ManyToManyField(blank=True, null=True, to='Boleteria.Funcion'),
        ),
    ]
