# Generated by Django 2.1.7 on 2019-06-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boleteria', '0004_auto_20190618_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='Funcion',
            field=models.ManyToManyField(blank=True, to='Boleteria.Funcion'),
        ),
    ]
