# Generated by Django 2.1.7 on 2019-06-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0018_auto_20190623_0848'),
        ('Boleteria', '0007_pelicula_exhibicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBoletos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boleteria.Boleto')),
                ('butaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boleteria.Butaca')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boleteria.Funcion')),
                ('lineaVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.LineaVenta')),
            ],
            options={
                'verbose_name': 'RegistroBoletos',
                'verbose_name_plural': 'RegistroBoletoss',
            },
        ),
    ]
