# Generated by Django 2.1.7 on 2019-06-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boleteria', '0008_registroboletos'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroboletos',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='Pagado?'),
            preserve_default=False,
        ),
    ]
